apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: redis:8
          command:
            - /bin/sh
            - -c
            - redis-cli -h redis incrby counter 5000 && sleep 10 && redis-cli -h redis incrby counter 5000